//
// Created by Volodymyr Ananiev <volodymyr.ananiev@gmail.com> on 29.10.2021.
//

#ifndef CASSETTEFLOW_FIRMWARE_COMPONENTS_MINIMODEM_MINIMODEM_CONFIG_H
#define CASSETTEFLOW_FIRMWARE_COMPONENTS_MINIMODEM_MINIMODEM_CONFIG_H

// excluding line end character (LF)
#define TAPEFILE_LINE_LENGTH        (29)

#endif //CASSETTEFLOW_FIRMWARE_COMPONENTS_MINIMODEM_MINIMODEM_CONFIG_H
