//
// Created by Volodymyr Ananiev <volodymyr.ananiev@gmail.com> on 02.10.2021.
//

#ifndef CASSETTEFLOW_FIRMWARE_MAIN_CONFIG_H
#define CASSETTEFLOW_FIRMWARE_MAIN_CONFIG_H

#define CONFIG_WIFI_SSID "SA906"
#define CONFIG_WIFI_PASSWORD "458C60F416"

#endif //CASSETTEFLOW_FIRMWARE_MAIN_CONFIG_H
