//
// Created by Volodymyr Ananiev <volodymyr.ananiev@gmail.com> on 02.10.2021.
//

#ifndef CASSETTEFLOW_FIRMWARE_MAIN_CONFIG_H
#define CASSETTEFLOW_FIRMWARE_MAIN_CONFIG_H

#define CONFIG_WIFI_SSID "SA906"
#define CONFIG_WIFI_PASSWORD "458C60F416"

#define FIRMWARE_VERSION_STRING "CassetteFlow ESP32 v1.1.0 ( 12/26/2025 )"

#endif //CASSETTEFLOW_FIRMWARE_MAIN_CONFIG_H
